### ISSUE TITLE
Forward signing proxy... for client certs

### ISSUE THREAD

**Issue by timgent** [gambol99/keycloak-proxy#112]
Just an idea - forward signing proxy can do keycloak auth at the min, could configure it to also do auth with client certificates

**Comment by gambol99** [comment]
Just to be clear ... you want an extra option to use a client certificate in the TLS client config and 'perhaps' reload the certificate when the client cert comes close to expiration?

**Comment by timgent** [comment]
Yeah. What do you think? Not sure if it is OTT or not.

**Comment by gambol99** [comment]
@timgent add in PR #114

**Comment by timgent** [comment]
Nice :)
