### ISSUE TITLE
`--forwarding-domains` doesn't work as described

### ISSUE THREAD

**Issue by chrisns** [gambol99/keycloak-proxy#120]
`--forwarding-domains=foo.bar.com`
signs requests to `foo.bar.com`

according to the documentation
`--forwarding-domains=bar.com`

should also sign requests to `foo.bar.com` but it doesn't

sadface.

**Comment by gambol99** [comment]
fixed in https://github.com/gambol99/keycloak-proxy/releases/tag/v1.2.4-rc1
