### ISSUE TITLE
allow the upstream "Authorization" header to not be sent

### ISSUE THREAD

**Issue by cameronbraid** [gambol99/keycloak-proxy#132]
I am wanting to use keycloak-proxy with grafana proxy auth module. 

 I have run into an issue where grafana detects the Authorization header and attempts to verify it as a grafana api key, and therefore throws an error.

One option could be to get grafana to disable api key checking, but I thought it may be simple to do it in here  ?

**Comment by gambol99** [comment]
@cameronbraid sorry for the delay ... So you need an option to strip the authorization header before proxying on? ..

**Comment by cameronbraid** [comment]
Yeah  that's what in after. 

I have impenetrable a workaround with an nginx proxy that strips the header and it works successfully. 

proxy_set_header        Authorization "";

But I'd rather no have to have two proxies :)

**Comment by gambol99** [comment]
@cameronbraid  ... --enable-authorization-header was merged into release v1.2.7, it's enabled by default ... but you can --enable-authorization-header=false (or in config file) to switch it off

**Comment by gambol99** [comment]
hi @cameronbraid, can i close the ticket as 'fixed'?

**Comment by cameronbraid** [comment]
I havn't managed to test the change yet, but it looks good to me
