### ISSUE TITLE
Allow tokens from different clients

### ISSUE THREAD

**Issue by boldt** [gambol99/keycloak-proxy#135]
I want to allow tokens from different clients. How can I do that? I tried the following:

```
match-claims:
  aud: (.*?)
```

I am getting the log:

```
INFO[0000] the token must container the claim: aud, required: (.*?) 
```

After calling the endpoint with an token created by another client-id, I am getting:

```
ERRO[0040] access token failed verification              client_ip=w.x.y.z.  error=oidc: JWT claims invalid: invalid claims, 'aud' claim and 'client_id' do not match, aud=<otherClientId>, client_id=<configuredClientId>
```

He still claims, that the aud must be `<configuredClientId>`

**Comment by gambol99** [comment]
@boldt sorry for the delay ... Looks like its hard coded at the moment (https://github.com/gambol99/keycloak-proxy/blob/master/middleware.go#L298) ... Might be an idea though to drop the audience check and leave to the optional in match-claims options instead ... Perhaps inject by default in match-claims to keep the behavior, but with the option permitting an override ..

**Comment by gambol99** [comment]
Actually; it appears to be a requirement of the go-oidc lib https://github.com/coreos/go-oidc/blob/master/oidc/verification.go#L83 ... Out of interest, whats the use case? ...
