### ISSUE TITLE
cookie-domain bug

### ISSUE THREAD

**Issue by boyand** [gambol99/keycloak-proxy#136]
Currently the cookie-domain flag is set as a StringSlice. Therefore if you pass ```--cookie-domain foo.com``` on startup, dropping a cookie fails with:

```net/http: invalid Cookie.Domain "[foo.com]"; dropping domain attribute```

Using a config file works correctly.

**Comment by gambol99** [comment]
hi @boyand ... cheers for spotting this one, I've raised https://github.com/gambol99/keycloak-proxy/pull/137 which should fix the issue
