### ISSUE TITLE
Basic Auth support

### ISSUE THREAD

**Issue by totallyunknown** [gambol99/keycloak-proxy#141]
It would be great, if it would be possible to authenticate a upstream server with basic auth. 

```
--upstream-username=foobar
--upstream-password=supersecret
```

I've tried `--headers` but it's failing:

```
--headers "authorization=Basic <redacted>"
[error] invalid tag 'authorization=Basic <redacted>=' should be key=pair
```

**Comment by gambol99** [comment]
hi @totallyunknown  ... what version were you using? ..
