### ISSUE TITLE
login handler only called locally

### ISSUE THREAD

**Issue by boyand** [gambol99/keycloak-proxy#143]
Hi, 

I was just looking at the latest changes. The localhost origin requirement for the login handler caught my eye. What is the motivation behind it? Do you expect something else to terminate the client connection and proxy locally to the keycloak-proxy. Maybe it makes sense to be explained in more details in the docs?

**Comment by gambol99** [comment]
hi @boyand ... perhaps I was being overly cautious. The reason for this handler was to satisfy a niche requirement internally, I never really like the idea of it to be honest, as i don't like the idea of external user piggy-backing on the client-id/client-secret. Though i actually have to revert some of it anyhow, due it still being a internal requirement; the --enable-login-handler will remain, but the localhost will be dropped.

**Comment by boyand** [comment]
Hey @gambol99. Thanks for clarifying and relaxing the logic. I think it is a pretty good feature allowing for client credentials grant - especially for 'own' web/mobile clients where you don't want to go for delegation but straight auth.
