### ISSUE TITLE
Missing Prometheus functions?

### ISSUE THREAD

**Issue by max-allan-surevine** [gambol99/keycloak-proxy#148]
Hi, I get an error which I think is due to MustRegisterorGet being deprecated : 
https://github.com/prometheus/client_golang/compare/v0.8.0...master#diff-6223e8ae8180a02a4024a006b8e5f2f8

```
go get -u github.com/gambol99/keycloak-proxy
# github.com/gambol99/keycloak-proxy
src/github.com/gambol99/keycloak-proxy/middleware.go:71: undefined: prometheus.MustRegisterOrGet
```
I'd try and fix it but I have never written any Go before!

**Comment by max-allan-surevine** [comment]
Made a fork which builds. No idea if the proxy works or not yet!
https://github.com/max-allan-surevine/keycloak-proxy

**Comment by gambol99** [comment]
I can't seem to replicate this ... Are you build using godeps? ... i.e. i'm guessing your building from source as you've suggested they've removed the method ...

```shell
[jest@starfury keycloak-proxy]$ curl -s https://127.0.0.1:3000/oauth/metrics -k | grep ^http_request_total
http_request_total{code="200",method="GET"} 7
http_request_total{code="307",method="GET"} 3
http_request_total{code="500",method="GET"} 6
```

**Comment by max-allan-surevine** [comment]
Go is totally new to me.
Fire up new AWS instance, run this :
```
yum -y install golang
mkdir -p go/bin
cd go
export GOPATH=`pwd`
export GOBIN=$GOPATH/bin
export PATH=$GOPATH:$GOBIN:$PATH
go get -u github.com/tools/godep
go get -u github.com/gambol99/keycloak-proxy
```
And then the error above.
From what I've read about godep it should be doing something with getting the right version of dependencies, like Prometheus, but it seems to grab the latest. Rather than latest release (1.8 I think it was) that still had the MustReg.. functions in. 
If I get my fork instead, then it completes without the error. I can cd into the directory and "make static" and get a binary that seems to be working (so far)!

**Comment by gambol99** [comment]
```shell
docker run -ti --rm centos bash
[root@0d3433f212a4 /]# yum install golang git make
...
[root@0d3433f212a4 /]# export GOPATH=$HOME/go
[root@0d3433f212a4 /]# mkdir -p $GOPATH
[root@0d3433f212a4 /]# export PATH=$PATH:$GOPATH/bin
[root@0d3433f212a4 /]# go get -u github.com/tools/godep
[root@0d3433f212a4 /]# go get -d github.com/gambol99/keycloak-proxy
[root@0d3433f212a4 /]# cd ~/go/src/github.com/gambol99/keycloak-proxy
[root@0d3433f212a4 keycloak-proxy]# godep go build

Alternatively, if you have docker in the box it's probably easier just to use the docker-build 

[jest@starfury keycloak-proxy]$ GOVERSION=1.7.3 make docker-build
--> Compiling the project
docker run --rm -v /home/jest/go/src/github.com/gambol99/keycloak-proxy:/go/src/github.com/gambol99/keycloak-proxy \
	-w /go/src/github.com/gambol99/keycloak-proxy -e GOOS=linux golang:1.7.3 make static
--> Go Version
go version go1.7.3 linux/amd64
--> Installing build dependencies
--> Compiling the static binary
mkdir -p bin
CGO_ENABLED=0 GOOS=linux godep go build -a -tags netgo -ldflags "-w -X main.gitsha=635ca2c" -o bin/keycloak-proxy
[jest@starfury keycloak-proxy]$ ls bin/
keycloak-proxy
```
You can check the Makefile to find the complete build commands ... but effectively _godep go build_

**Comment by gambol99** [comment]
can i assume this closed? @max-allan-surevine

**Comment by max-allan-surevine** [comment]
No, I don't think it's closed at all. I cleared out the entire go folder and started again. It still doesn't pull the correct version of Prometheus.
[root@ip-10-66-2-145 ~]# cd go
[root@ip-10-66-2-145 go]# rm -rf *
[root@ip-10-66-2-145 go]# export GOPATH=`pwd`
[root@ip-10-66-2-145 go]# export PATH=$PATH:$GOPATH/bin
[root@ip-10-66-2-145 go]# go get -u github.com/tools/godep
[root@ip-10-66-2-145 go]# go get -d github.com/gambol99/keycloak-proxy
[root@ip-10-66-2-145 go]# cd ~/go/src/github.com/gambol99/keycloak-proxy
[root@ip-10-66-2-145 keycloak-proxy]# godep go build
# github.com/gambol99/keycloak-proxy
./handlers.go:307: undefined: "net/http".MethodPost
./middleware.go:67: undefined: prometheus.MustRegisterOrGet
./oauth.go:73: undefined: "net/http".MethodGet
godep: go exit status 2

Exactly the same error (and more!!) following your instructions as mine. Except you added an extra step of cd  into the directory and do a build instead of letting "go get" do it.
It looks like someone has edited and pushed back to the project the middleware file since I submitted my issue but not removed the MustRegisterOrGet deprecated function...

**Comment by max-allan-surevine** [comment]
OK, I've also tried this on a CentOS instance and it works. So, it looks like it's the Amazon Linux that causes the fail. 
Yum gets go v 1.5.3 on Amazon and 1.6.3 on Centos. Maybe it's that...? It does seem like a good idea to be removing deprecated functions though!
As I can make it build on Centos, I'll close the issue. Not exactly satisfactory but not the end of the world.
