### ISSUE TITLE
provide an option to use the host header for PROXY_REDIRECTION_URL

### ISSUE THREAD

**Issue by cameronbraid** [gambol99/keycloak-proxy#182]
I wish to use the same proxy instance for multiple domains, which can't be done due to the hard coded PROXY_REDIRECTION_URL env var or command line argument.

Could keycloak support a flag to generate this from the request's host header ?

**Comment by gambol99** [comment]
Yeah .. i recall wanting to make the exact change, the underlining lib [go-oidc](github.com/coreos/go-oidc) doesn't expose the redirection url post client creation though. I've raised a [#PR130](https://github.com/coreos/go-oidc/pull/130)

**Comment by cameronbraid** [comment]
ok, thanks

**Comment by gambol99** [comment]
This should be fixed in master branch. If no redirection-url is provided it will use the **Host** header or the **X-Forwarded-Host** header .. Let me know if you have any issues :-)
