### ISSUE TITLE
Does not include the # hash of the original page in the redirect parameter 

### ISSUE THREAD

**Issue by hod-shcraigen** [gambol99/keycloak-proxy#186]
When a url contains a hash fragment the redirect_uri does not include the hash string
eg when visiting a Keycloak protected location...

`http://test.com/#!/something`

...the KC login screen is displayed, but the query string parameter for redirect_uri does not include the hash so you end up with...

`https://proxy.com/auth/realms/tet/protocol/openid-connect/auth?client_id=abc&redirect_uri=https%3A%2F%2Ftest.com%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=Lw%3D%3D#!/financial-status-calc`

...notice how the redirect_uri is near the beginning of the query string parameters but the hash fragment is tagged onto the end.

**Comment by jits** [comment]
Note: the use of the `#` fragment identifier is only really for client purposes and is not intended to be used by a server in any form.

From https://en.wikipedia.org/wiki/Fragment_identifier:

> Clients are not supposed to send URI-fragments to servers when they retrieve a document, and without help from a local application (see below) fragments do not participate in HTTP redirections.

So I believe the proxy is doing the right thing by cutting it out.

In Angular, you can choose to not use the `#!` and instead rely on HTML5 push state, by doing this in a config block:

```js
$locationProvider.html5Mode(true);
```

([ref](https://docs.angularjs.org/api/ng/provider/$locationProvider))

You then need to make sure your web server can serve any endpoint in your app.

If you can't use HTML5 push state for whatever reason, you will need to have a special redirect endpoint served by your web server, instead.

**Comment by hod-shcraigen** [comment]
Thanks for your response and yes I am aware that I could change Angular to solve the issue - for browsers that support it, which does not include IE9 (I don't want to support IE9 so lets not get into the whole developing for old browsers debate). But the fact still remains that KeyCloak/KeyCloak-Proxy takes the client browser away from the intended URI including the # fragment, authenticates it and returns it to a location which does not include a hash - therefore a bug.

Lets look at it differently, if I have a non angular/non javascript page which is very long and I need to link to a particular portion of the page then I might use a #fragment to do that, so users can follow a link both the page and a specific portion of that page. If the link is outside of KeyCloak but the content being linked to is protected by KC then your argument is that it is correct behaviour to click the link (with #)  be authenticated and then return to the same page without it.

eg

This link: `boringsite.com/verylongpage.html#articleinthemiddle` would take me to KC, and then back to `boringsite.com/verylongpage.html` thus removing basic link functionality.

Therefore I would ask you reconsider the issue.

**Comment by jits** [comment]
@hod-shcraigen – my point is simply that servers are not _required_ (or expected) to handle the `#` fragment in URLs.

Having said that, as you suggest, this is not a typical case of a server responding to a request with a `#` fragment in the URL; I guess the main point is you're _passing_ a URL around as data, and then expecting the final redirect to use this data, verbatim, as the redirect location. Practically speaking, this makes sense. The Wikipedia page (which references the spec) _seems_ to suggest otherwise, with the "[…] fragments do not participate in HTTP redirections.", but this is a little ambiguous/unclear.

So yes, I'd agree this should be fixed, if @gambol99 agrees :)

**Comment by gambol99** [comment]
hiya ... I did take a look at this yesterday as I wasn't sure if it was a validate url or not. First thing, I struggled to get the browser (firefox/chrome) to even send anything post the '#', even curl refuses to send it. The only means of getting this into a redirect_uri would be to encode as %23 ... but that's an app responsibility.

**Comment by hod-shcraigen** [comment]
Yes it is the app's responsibility to encode/preserve the redirect URI correctly in it's entirety but in this case the app in question is KC or KC-proxy. We don't set the redirect_uri - KC does?

If it's a configuration issue, then please enlighten us.

Again in the scenario of a portion of a long page being linked to via a #fragment should KC not preserve that piece of information?

**Comment by stefancocora** [comment]
The way I understand this is that if your original URL doesn't have the hash url encoded then the client won't even send it to keycloak.
@hod-shcraigen please put in this ticket some actual URLs that we can test.

**Comment by hod-shcraigen** [comment]
@stefancocora how can the original url be encoded? It doesn't need to be encoded and nor should it be we're talking about the actual current url the browser is looking at being put into the KC process in a form that does not seem capable of preserving the hash.

I will paste a url on the BAU board of an actual example of the issue.

**Comment by stefancocora** [comment]
When you have a chance, please put in the ticket the test you've done  with real URLs where the entire url including the part after the hash gets sent to the server side.
@hod-shcraigen  notice how the client doesn't even send the part after the hash to the server.
```
curl -v -I  https://encrypted.google.com/something#test
...
> HEAD /something HTTP/1.1   <=============
> Host: encrypted.google.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
...
```

**Comment by chrisns** [comment]
@hod-shcraigen this may help you:
https://scotch.io/tutorials/pretty-urls-in-angularjs-removing-the-hashtag

also
https://github.com/UKHomeOffice/keycloakjs-redirect may help you, it's used by https://github.com/UKHomeOffice/removals_wallboard

Though that doesn't care about preserving the url since it is a single page app with no routing.

Presuming it's a HO product, and going to go through the GDS framework it might be good to have a chat about what+why you're needing to use frontend JS.

~chris

**Comment by hod-shcraigen** [comment]
@chrisns Thanks Chris, as I stated previously I do already know how to remove the hash from the Angular URL. I have also had many discussions internally on why this project is to use Angular (I didn't choose it) and it was deemed OK. However the issue would still be present in IE9 which doesn't support the HTML5 pushState functionality required.

So let me ask again is it OK that a link (Angular app or otherwise) that has a hash fragment is not preserved after being put through KC?

**Comment by jits** [comment]
> So let me ask again is it OK that a link (Angular app or otherwise) that has a hash fragment is not preserved after being put through KC?

Perhaps a question to pose to browser manufacturers like Chrome, Firefox etc, since the browser is stripping out the `#` fragment before sending the request to the server.

**Comment by chrisns** [comment]
Apologies, I missed that bit of conversation in the history.
if you wanted a work around, you could open a new window/popup for the keycloak journey
or pass a not `#` to the redirect and handle that coming back server side and deal with your urls will be something like `example.com/my_url#another page`

**Comment by hod-shcraigen** [comment]
Thanks all, if I'm understanding correctly this issue cannot be fixed by KC-Proxy - because this is an entirely server side solution and the client (the browser not the app) doesn't send the hash.

Initially we were using the KC-Angular/JS plugin but @stefancocora directed us to use KC-proxy as this would be much simpler to implement, he must have forgotten that it cannot work with Angular or other javascript based projects relying on the hash.
