### ISSUE TITLE
Microsoft ADFS issue

### ISSUE THREAD

**Issue by dmzaytsev** [gambol99/keycloak-proxy#198]
I tried to use keycloak-proxy with Microsoft ADFS server and faced an issue.
ADFS server rejects token requests if `client-id/client_secret` used more than in one place
keycloak-proxy sends `client-id/client_secret` twice in the Authorization header and in the request body

I guess the problem is here 
https://github.com/gambol99/keycloak-proxy/blob/master/oauth.go#L39
Would it possible to add a configuration option to set the auth method for token requests?

**Comment by gambol99** [comment]
Sorry for the delay ... 

Admittedly I doubt have access to run ADFS to verify the behavior. Although, I'm the sure how the authorization header (formed from the client_id/secret) would be the root cause. Are there any specific errors thrown in verbose mode? ...

**Comment by dmzaytsev** [comment]
yes I see the error message when keycloak-proxy tryes to exchange the auth code to the token

>ERRO[0008] unable to exchange code for access token  Invalid_request: MSIS9631: Invalid OAuth request received. several methods have been made to client authentication.
