### ISSUE TITLE
Docker registry image

### ISSUE THREAD

**Issue by naveensrinivasan** [gambol99/keycloak-proxy#203]
IMO the quickest way to anyone to try is to pull a docker image and run the application. Though the project provides a Docker file, it would be great to have an existing docker registry image that users can pull. Thoughts?

Thanks

**Comment by gambol99** [comment]
Hi @naveensrinivasan ... every tagged build and master update is automatically built ... https://quay.io/repository/gambol99/keycloak-proxy

**Comment by naveensrinivasan** [comment]
@gambol99 Thanks, did a PR with that information  #204 included in the `README.md`
