### ISSUE TITLE
Feature request: don't always redirect

### ISSUE THREAD

**Issue by chrisns** [gambol99/keycloak-proxy#25]
Please could there be a configuration setting that would prevent the proxy redirecting on no-auth and just return valid HTTP status code (`401 Unauthorized` and `403 Forbidden`)?
Perhaps optionally combined with when the request `Content-Type: application/json` (or maybe even wildcarded to `application/*`?

This is particularly useful for APIs that javascript access since the browser won't permit the cross origin request to the keycloak service (without whitelisting all potential clients there), so it allows a javascript front end to better handle the status and direct the user to authenticate.

**Comment by gambol99** [comment]
A new configuration option --no-redirects has been added #27
