### ISSUE TITLE
Additional root certificate authority

### ISSUE THREAD

**Issue by jangaraj** [gambol99/keycloak-proxy#256]
I need to verify cert of my upstream (`skip-upstream-tls-verify: false`), but I use my own CA + I need my system provided CAs, because google OAuth => I need some param (`additional-ca-certificate` ), where can I specify additional CA cert(s), which will be added to root CAs.

Some discussion about this problem - https://groups.google.com/forum/#!topic/golang-nuts/4qn5XW6SG0M

**Comment by gambol99** [comment]
hi @jangaraj .. I'm guessing this would involve another config and loading a CA into the tlsConfig around [here](https://github.com/gambol99/keycloak-proxy/blob/master/server.go#L513-L543). I'm happy to take a look at it ... though a PR is always welcome :-)

**Comment by jangaraj** [comment]
Yes, there must be created `tlsconfig.RootCAs`.

**Comment by gambol99** [comment]
hi @jangaraj .. this should be address in #260. Let me know if you have any issues

**Comment by jangaraj** [comment]
LGTM, tested on my system and it works. 👍 
Thank you.
