### ISSUE TITLE
Unable to configure CORS in the proxy config

### ISSUE THREAD

**Issue by abhishekraghav** [gambol99/keycloak-proxy#258]
I am stuck is the CORS Configuration. Not really sure, how can i get that configured in my current setup.

Pasting the configuration i tried:

```
{
	"discovery-url": "https://keycloak-example-url/auth/realms/SAMPLE",
	"client-id": "sample",
	"client-secret": "sample-secret",
	"listen": ":3000",
	"enable-refresh-token": true,
	"redirection-url": "http://localhost:3000/",
	"upstream-url": "http://my-app-url/appContext/",
	"secure-cookie": false,
	"enable-logging": true,
	"verbose": true,
	"resources": [
		{
			"uri": "/protected/*"
		}
	],
	"cors-origins": ["*"],
	"cors-headers": ["Access-Control-Allow-Origin","Access-Control-Allow-Headers"],
	"cors-methods": [],
	"cors-credentials": true,
	"cors-max-age": "1h",
	"cors-methods": [
		"GET",
		"POST",
		"HEAD",
		"OPTIONS"
	],
	"add-claims": [
		"email"
	]
}

```
Everything works fine as per above config, only the CORS part i am not getting it right. Please see if thats the right configuration. I should be seeing the CORS headers in the response headers in the reponse, but i couldn't see any such header in the browser.
Which is why i am seeing CORS exception when Keycloak proxy tries to load a secured resource and it  tries to navigate to auth server URL, i see this as exception in my browser:

![image](https://user-images.githubusercontent.com/19988460/28753563-8d699dc8-7553-11e7-94d7-6e47f9e3360b.png)

I really appreciate any  help on this. 
Thanks a lot.

**Comment by jangaraj** [comment]
Why you have double `cors-methods` in your config?
```
        "cors-methods": [],
         ....
	"cors-methods": [
		"GET",
		"POST",
		"HEAD",
		"OPTIONS"
	],
```

**Comment by abhishekraghav** [comment]
Hey @jangaraj 
Thanks for replying, its a copy paste error. But even after modifying this, i am still seeing the same CORS exception on the browser.

**Comment by gambol99** [comment]
hi @abhishekraghav ... sorry for the delay ... the cors middleware is setup [here](https://github.com/gambol99/keycloak-proxy/blob/master/server.go#L171-L180) ... though the code is import from [here](https://github.com/rs/cors/blob/master/cors.go#L183-L203) ... Can you follow the logic just to check if it's a bug on the proxy's part or the lib isn't giving you what you expect?

**Comment by dalu** [comment]
I have this same issue and it isn't fixed, so Idk why this is closed.

**Comment by dalu** [comment]
The issue was, for me, if `cors-origins: ['*']` but no `cors-headers` where present,
the `Access-Control-Allow-Origin` would be missing.
With both set to `['*']` , `Access-Control-Allow-Origin: *, *` is the response header.
Well, 1 * is better than 2 but not needed.
