### ISSUE TITLE
Configurable timeouts

### ISSUE THREAD

**Issue by jangaraj** [gambol99/keycloak-proxy#263]
At the moment `IdleTimeout` is used + it's hardcoded: https://github.com/gambol99/keycloak-proxy/blob/1741a5b3fdf0c5e80656fa64e4a88756d57a390d/server.go#L336-L340

Could you add options to set value of `ReadTimeout, WriteTimeout, IdleTimeout` please?

Upstream proxy also can implement some timeouts `TLSHandshakeTimeout, ResponseHeaderTimeout, ExpectContinueTimeout`:
https://github.com/gambol99/keycloak-proxy/blob/1741a5b3fdf0c5e80656fa64e4a88756d57a390d/server.go#L552-L556

Reference:
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

**Comment by gambol99** [comment]
fixed in #268
