### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by Vad1mo** [gambol99/keycloak-proxy#265]
Would it be possible to add environment variables support as an third option next to CLI and Config file. 

The reason is that we created a wrapper service https://github.com/8gears/keycloak-auth-proxy  around the keycloak java version with flexible config options and decent defaults. 

We would like to switch to this service as we find it more elaborated and production ready.

**Comment by jangaraj** [comment]
Some env variables for some options are available. See `keycloak-proxy help`:

```
GLOBAL OPTIONS:
   --config value                      path the a configuration file [$PROXY_CONFIG_FILE]
```
=> env variable is `$PROXY_CONFIG_FILE` for this option
