### ISSUE TITLE
policy checking

### ISSUE THREAD

**Issue by Vad1mo** [gambol99/keycloak-proxy#269]
I create an authorization resource javascript policy and check if use has a given attribute. The evaluation is working fine. Now I want that the auth proxy checks/requests the resource type `urn:docs:resources:content` or associates the resource URI with the --resource  arg of auth-proxy.

it  that possible?

**Comment by dalu** [comment]
I might be wrong but isn't the feature described in #155 ?
The oauth2 world and Java in general is quite alien to me.

**Comment by gambol99** [comment]
hi @Vad1mo ... UMA support was put down and a potential feature, but was never implemented
