### ISSUE TITLE
using http_proxy in order to contact KeyCloak

### ISSUE THREAD

**Issue by adamlis-mirantis** [gambol99/keycloak-proxy#271]
https://github.com/gambol99/keycloak-proxy/blob/1741a5b3fdf0c5e80656fa64e4a88756d57a390d/server.go#L609

There is call being done to: oidc.FetchProviderConfig(hc, r.config.DiscoveryURL)

Am I seeing correctly that this code would try to do DNS resolve of r.config.DiscoveryURL and try to reach it directly?

In my case, VM I'm running this Docker image is strictly behind proxy and I need to contact all URLs via proxy.

I'm getting errors:
{"level":"info","ts":1504131428.8672457,"caller":"keycloak-proxy/server.go:608","msg":"attempting to retrieve configuration discovery url","url":"https://myURL"}
{"level":"warn","ts":1504131428.873323,"caller":"keycloak-proxy/server.go:612","msg":"failed to get provider configuration from discovery","error":"Get https://myURL/.well-known/openid-configuration: dial tcp: lookup myServer on 192.168.252.2:53: server misbehaving"}

Docker daemon itself is started with needed proxy setting and it's using them correctly (to retrieve images).

**Comment by jangaraj** [comment]
IMHO https://golang.org/pkg/net/http/#ProxyFromEnvironment will be good solution. Standard  environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY can be used:
```
        // step: create a idp http client
	hc := &http.Client{
		Transport: &http.Transport{
                        Proxy: http.ProxyFromEnvironment,
			TLSClientConfig: &tls.Config{        
				InsecureSkipVerify: r.config.SkipOpenIDProviderTLSVerify,
			},
        },
		Timeout: time.Second * 10,
}
```

**Comment by adamlis-mirantis** [comment]
Thanks for reply.

Seems it anyway tries to do DNS resolving. In my case all traffic just need to go via proxy.

I've done simple test:
`
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# curl -q https://www.google.com
curl: (6) Could not resolve host: www.google.com
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# . /home/ubuntu/proxy.sh 
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# 
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# curl -q https://www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.de/?gfe_rd=cr&amp;ei=cdynWebgFeiA8QeXjLngBA">here</A>.
</BODY></HTML>
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# ./diff/c16aecd8883fdd61807a1919185eb6c5cbbaebf60d94fb7c84bf847fbfbe1ff2/keycloak-proxy  --config /home/ubuntu/keycloak-proxy-config-local.yaml 
{"level":"info","ts":1504173180.8688688,"caller":"keycloak-proxy/server.go:78","msg":"starting the service","prog":"keycloak-proxy","author":"Rohith","version":"v2.1.0-rc3 (git+sha: 0fc5cd4, built: 30-08-2017)"}
{"level":"info","ts":1504173180.869205,"caller":"keycloak-proxy/server.go:608","msg":"attempting to retrieve configuration discovery url","url":"https://some.domain.just.for.show.com/auth/realms/realm-name"}
{"level":"warn","ts":1504173180.8786542,"caller":"keycloak-proxy/server.go:612","msg":"failed to get provider configuration from discovery","error":"Get https://some.domain.just.for.show.com/auth/realms/realm-name/.well-known/openid-configuration: dial tcp: lookup some.domain.just.for.show.com on 127.0.0.53:53: server misbehaving"}
^C
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# 
`

And if I remove all 'nameserver' sections from `/etc/resolv.conf`:
`
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# ./diff/c16aecd8883fdd61807a1919185eb6c5cbbaebf60d94fb7c84bf847fbfbe1ff2/keycloak-proxy  --config /home/ubuntu/keycloak-proxy-config-local.yaml 
{"level":"info","ts":1504173317.8835802,"caller":"keycloak-proxy/server.go:78","msg":"starting the service","prog":"keycloak-proxy","author":"Rohith","version":"v2.1.0-rc3 (git+sha: 0fc5cd4, built: 30-08-2017)"}
{"level":"info","ts":1504173317.88406,"caller":"keycloak-proxy/server.go:608","msg":"attempting to retrieve configuration discovery url","url":"https://some.domain.just.for.show.com/auth/realms/realm-name"}
{"level":"warn","ts":1504173317.8871384,"caller":"keycloak-proxy/server.go:612","msg":"failed to get provider configuration from discovery","error":"Get https://some.domain.just.for.show.com/auth/realms/realm-name/.well-known/openid-configuration: dial tcp: lookup some.domain.just.for.show.com on [::1]:53: read udp [::1]:47107->[::1]:53: read: connection refused"}
{"level":"info","ts":1504173320.8874958,"caller":"keycloak-proxy/server.go:608","msg":"attempting to retrieve configuration discovery url","url":"https://some.domain.just.for.show.com/auth/realms/realm-name"}
{"level":"warn","ts":1504173320.8889158,"caller":"keycloak-proxy/server.go:612","msg":"failed to get provider configuration from discovery","error":"Get https://some.domain.just.for.show.com/auth/realms/realm-name/.well-known/openid-configuration: dial tcp: lookup some.domain.just.for.show.com on [::1]:53: read udp [::1]:42832->[::1]:53: read: connection refused"}
^C
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# 
`

In file `/home/ubuntu/proxy.sh` I have following (not showing exact values):
`
root@cloud-idp-demo-app-01:/var/lib/docker/aufs# cat /home/ubuntu/proxy.sh | sed -e 's/=.*$/=/g'

export http_proxy=
export https_proxy=
export no_proxy=

export HTTP_PROXY=
export HTTPS_PROXY=
export NO_PROXY=

root@cloud-idp-demo-app-01:/var/lib/docker/aufs#
`

**Comment by jangaraj** [comment]
Did you implement `Proxy: http.ProxyFromEnvironment,` ? I've posted only idea, current code doesn't use any HTTP_PROXY/HTTPS_PROXY env variable atm.
You are not able to execute DNS resolving through HTTP(S) proxy - that's UDP (TCP) traffic, not HTTP.
"local dnsmasq as DNS" doesn't sound like a good solution. Check doc https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/ probably `--dns=IP` will be better solution.

**Comment by adamlis-mirantis** [comment]
Sorry, I misunderstood your comment. I thought you said it is already implemented. 

So I'm not go developer so I'd not be able to help with implementation. But anyway as I understand it's confirmed, that currently project do not use http_proxy settings?

**Comment by jangaraj** [comment]
Proposed change https://github.com/jangaraj/keycloak-proxy/commit/4ff90cc7bb20d331c9c0a1afa3611b5d09498dd1. I've built Docker image for this my feature brand - `jangaraj/keycloak-proxy:proxy`. You will need to define env variable for the container, e.g.: 
```
-e HTTPS_PROXY=https://user:pass@ProxyServerAddress:Port
```
It'll be used only to contact IDP. I guess you will need the additional setting for DNS resolution (probably that `--dns=IP`). Feel free to email me - jan.garaj@gmail.com.

I'll create proper pull request later.

**Comment by jangaraj** [comment]
Fixed by https://github.com/gambol99/keycloak-proxy/pull/272
