### ISSUE TITLE
Question: xhr redirect to /oauth/authorize results in 500

### ISSUE THREAD

**Issue by dalu** [gambol99/keycloak-proxy#273]
I don't know where else to ask.
This is a good case for delegating the blame to the other party and me remaining in no-man's land.

I'm using Angular(4) with https://github.com/manfredsteyer/angular-oauth2-oidc
And it has an issue with the access token expiring. Token lifetime is 10 mins.

Well then in every xhr the token is sent with header `Authorization: Bearer <token>`
and when the token expires keycloak-proxy sends a status 307 (redirect temporary) response with a `Location: /oauth/authorize?state=<state>`. The redirect is then followed, of course, and it results in a 
```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: *
Vary: Origin
Date: Wed, 06 Sep 2017 16:57:43 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```
and this is the log

```
1.5047253340221033e+09  error   keycloak-proxy/middleware.go:147        session expired and access token refreshing is disabled {"client_ip": "127.0.0.1:55132", "email": "testuser", "expired_on": "2017-09-06 17:22:03 +0000 UTC"}
1.5047253340272334e+09  error   keycloak-proxy/handlers.go:68   failed to retrieve the oauth client for authorization   {"error": "missing client secret"}
```
because public client with implicit flow.

I'm guessing... fix the Angular token refreshing and this problem will be gone. Because keycloak-proxy serves as a firewall and if the token is expired, following redirects, it returns a status 500 so the xhr client knows something is wrong.

Ok this is probably solved still where would I ask questions? Stackoverflow? Anywhere where one could have a chance of receiving an answer.

**Comment by jangaraj** [comment]
Idea:  Disable redirects in keycloak-proxy (`--no-redirects`) and create a handler in your angular app, which will recreate/refresh access token when HTTP response code is 401 - Unauthorized.

**Comment by dalu** [comment]
good idea, now I just have to find out how to do that in the interceptor :)
thanks

**Comment by ernsheong** [comment]
I hit this as well. Arguably 401 would make sense across the board, in both cases, instead of 500.

**Comment by dalu** [comment]
You can 401 if, like jangaraj wrote, set `no-redirects: true` in yaml or, as he wrote, `--no-redirects=true`.
Then, instead of 307 redirect and then the xhr client getting a 500, it will get a 401.
