### ISSUE TITLE
Kube config file can't use.

### ISSUE THREAD

**Issue by Frank-auckland** [gambol99/keycloak-proxy#276]
I try to create a keycloak-proxy in kubernetes by the yaml file your provided in the kube directory, but it does not work.
First I created a secret named config by using config_sample.yml file.
My secret shows as follow:
Name:		config
Namespace:	sync
Labels:		<none>
Annotations:	<none>

Type:	Opaque

Data
====
forwarding.yml:	3439 bytes

Then I create a keycloak by the yaml file with the latest image, but I get the error shows as follows:
[error] invalid options, flag provided but not defined: -config /etc/secrets/forwarding.yml
flag provided but not defined: -config /etc/secrets/forwarding.yml

@gambol99

**Comment by jangaraj** [comment]
You need

    --config

instead of

    -config

**Comment by Frank-auckland** [comment]
Yes, I already used --config, but it not work.
![screenshot from 2017-09-15 09-42-40](https://user-images.githubusercontent.com/20473627/30457120-5c9b15a2-99fa-11e7-8d27-4a4bf64cf1db.png)

**Comment by jangaraj** [comment]
No idea. Maybe `--config=/etc/secrets/forwarding.yml` -> try to add that "=". 
BTW: you have published full config of your IdP client.

**Comment by gambol99** [comment]
hi @Frank-auckland ... was issue resolved? ... can i close the ticket

**Comment by Frank-auckland** [comment]
I give up, it still doesn't work, by our team change to another solution. So you can close it. If our team come back to this and there still have the problem, could I reopen it?
