### ISSUE TITLE
'aud' claim and 'client_id' do not match

### ISSUE THREAD

**Issue by ernsheong** [gambol99/keycloak-proxy#277]
Hi there,

I have two Keycloak clients, one for the frontend (public), and another for the backend API (bearer-only).

Token is generated by the frontend client, and I want to use the backend client with keycloak-proxy.

However, this doesn't seem to be supported. I get an error that aud claim and client_id do not match. 

Is there a way around this? Thanks

**Comment by jangaraj** [comment]
README:

> ClientID & Secret
> 
> Note, the client secret is optional and only required for setups where the oauth provider is using access_type = confidential; if the provider is 'public' simple add the client id. Alternatively, you might not need the proxy to perform the oauth authentication flow and instead simply verify the identity token (and potential role permissions), in which case, again just drop the client secret and use the client id and discovery-url.

Did you use the same _client-id_ and _discovery-url_ config for backend/frontend keycloak-proxy?

**Comment by jangaraj** [comment]
Did you find any solution?

**Comment by ernsheong** [comment]
Actually, the default security proxy supports this feature. http://www.keycloak.org/docs/3.3/server_installation/topics/proxy.html

But the default security proxy has other snags. So take your pick.

For now I figured I need to move faster and moving to Firebase authentication... Thanks though :)
