### ISSUE TITLE
prevent HTTP 413

### ISSUE THREAD

**Issue by pschulten** [gambol99/keycloak-proxy#285]
@gambol99 Thanks for this project.
Is it possible to not send the Cookie Header to upstream?
In my current use-case I have no control on upstream and it has a very conservative header size policy :( 
With encryption and refresh tokens the Cookie header is too large for upstream and it sends an 413

**Comment by jangaraj** [comment]
How do your cookie sizes look like in the browser? There was my issue and my PR, which increase the effective size of data in the cookies - https://github.com/gambol99/keycloak-proxy/issues/278 - Do you use latest master branch version?

**Comment by pschulten** [comment]
Thanks for this feature @jangaraj . I saw that and compiled from latest master branch but that didn't help in my case. The Cookie payload was around 3.8k. I guess my upstream has a hard header limit of 4k for all headers combined. I fixed it by stripping my JWT payload to the absolute minimum but It would be nice if the keycloak-proxy provides a switch to drop the openidc cookies on reverse proxying.

**Comment by jangaraj** [comment]
I agree. I have had a similar issue, but I was able to increase header size limit in my infrastructure. My suggestion:
```
cookie-blacklist:
   - kc_access*
   - kc_state*
```

**Comment by gambol99** [comment]
hi @pschulten ... i've started a PR to add the functionality #287 .. just need to fix up the unit test but i should have this available by the weekend

**Comment by gambol99** [comment]
fixed in #287

**Comment by jangaraj** [comment]
Note about potential cookie suffix: https://github.com/gambol99/keycloak-proxy/commit/81c7892b906ae65edbf9a62d65e375084bc44f8d

**Comment by gambol99** [comment]
good spot @jangaraj !!!! ... i'll amend the check and update the unit test ... thank you kindly :-)

**Comment by pschulten** [comment]
@gambol99 thank you very much. It works like a charm!
@jangaraj thanks for your support

**Comment by songokudbz** [comment]
Where did you add the cookie-blacklist?

**Comment by songokudbz** [comment]
Ty! Works. Nice solution.
