### ISSUE TITLE
TLS Client certificate for upstream

### ISSUE THREAD

**Issue by sybeck2k** [gambol99/keycloak-proxy#304]
I'm trying to use the option `--tls-client-certificate` to have the server to present back a client certificate to its upstream server.  In other words, I'm trying to have keycloak-proxy to do something equivalent of: `curl --key certs/client.key --cert certs/client.crt -k -i https://upstream_server`. But it seems that regardless of my configuration, the client certificate is not presented.
My use case is Kubernetes authentication: I'm using KC proxy to proxy OIDC authentication to the API - and K8S requires a client certificate to prevent header spoofing.
Am I misunderstanding the feature or I'm using a wrong configuration?

**Comment by aalubin** [comment]
We are using
-tls-private-key=<key file>
-tls-cert=<cert file>

for the same purpose

**Comment by jangaraj** [comment]
`--tls-client-certificate` is only for client certificates (mutual TLS) between `user <-> keycloak-proxy`. Client certificates for connection `keycloak-proxy <-> upstream-server` are not implemented at the moment.

**Comment by sybeck2k** [comment]
ok got it - I'm using as a workaround a stunnel. closing the issue!
