### ISSUE TITLE
Docker: keycloak-proxy startup fails if keycloak is taking long to start.

### ISSUE THREAD

**Issue by danbo** [gambol99/keycloak-proxy#307]
I'm trying keycloak-proxy in a docker image which fires things up in this order:

- postgres
- keycloak
- keycloak-proxy

Sometimes, keycloak-proxy fails hard if postgres and keycloak didn't fire up fast enough. From what I can tell, this is due to the timing that is hardcoded in server.go lines 628:645.

https://github.com/gambol99/keycloak-proxy/blob/1f5005e636edf8b3d59d0f87e74a7dbd9d09f8ea/server.go#L635

https://github.com/gambol99/keycloak-proxy/blob/1f5005e636edf8b3d59d0f87e74a7dbd9d09f8ea/server.go#L641

Can we make the timeout and retry count configurable?

**Comment by gambol99** [comment]
hi @danbo ... apologizes I didn't pickup on the issue quicker ... this was fixed in #315

**Comment by danbo** [comment]
Not to worry, i understand this is open source and people are doing their best.

I appreciate you looking into this.
