### ISSUE TITLE
The keycloak-proxy does NOT append upstream header in websocket request

### ISSUE THREAD

**Issue by markwiat** [gambol99/keycloak-proxy#310]
When I add in config file:
headers: 
  x-custom-header: sth

then the 'x-custom-header' is appended further in each request apart from websocket request.

I uses latest docker 'quay.io/gambol99/keycloak-proxy:latest' created at 2018-01-08.

The web socker request looks like below (some header was removed for clarity):

GET /ws/590/65z_va61/websocket HTTP/1.1
Host: lug.iot.iotgateway.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cache-Control: no-cache
Connection: Upgrade
Origin: https://some.iotgateway.com
Pragma: no-cache
Sec-Websocket-Key: iF3O7NMwwpoI47J8cVNBbg==
Sec-Websocket-Version: 13
Upgrade: websocket
X-Auth-Email: 
X-Auth-Expiresin: 2018-02-07 13:47:43 +0000 UTC
X-Auth-Groups: 
X-Auth-Roles: uma_authorization,account:manage-account,account:manage-account-links,account:view-profile
X-Auth-Subject: 1cddbe0f-8ee3-4d6e-ada9-9b569c36f543
X-Auth-Userid: someuser
X-Auth-Username: someuser

Could you please fix the problem?

**Comment by gambol99** [comment]
hi @markwiat ... this should be fixed in latest now. If you could check and confirm i'll happyly cut a release ..

**Comment by markwiat** [comment]
Thank you for the fix.

I've roughly checked it on docker: "Created": "2018-02-12T10:05:40.666937806Z"
and it seems to be ok.
The websocket requests also contain custom header.

**Comment by gambol99** [comment]
awesome .. thank you kindly @markwiat :-) .. i'll cut a release
