### ISSUE TITLE
Match multi value claims

### ISSUE THREAD

**Issue by avthart** [gambol99/keycloak-proxy#314]
Claims are currently parsed as string. Is it possible to support matching multi value claims?

**Comment by gambol99** [comment]
hi @avthart .. admittedly I wanted this myself, but it made the parsing more complicated and as yet haven't got around to revisiting

**Comment by stefan-improbable** [comment]
@gambol99 I've opened a PR https://github.com/gambol99/keycloak-proxy/pull/364 to fix this

**Comment by avthart** [comment]
@stefan-improbable Thx!
