### ISSUE TITLE
Prefix for /ouath/... endpoint

### ISSUE THREAD

**Issue by dlisin** [gambol99/keycloak-proxy#318]
In our application we are using URL sub-path: https://example.com/my-app

If you will try to use keycloak-proxy with such application - it will not work, because authentication URL will be incorrect: https://example.com/oauth/... instead of https://example.com/my-app/oauth/...

It would be great if keycloak-proxy will allow to specify prefix for /ouath endpoint. For example by introducing new parameter

**Comment by gambol99** [comment]
fixed in master ... i'll cut a release

**Comment by dlisin** [comment]
Thank you!
