### ISSUE TITLE
"missing client secret" error when using client with "public" access type

### ISSUE THREAD

**Issue by dlisin** [gambol99/keycloak-proxy#332]
In accordance with documentation client-secret argument is optional when using client with "public" access type. 

However I am getting error: 
```
keycloak-proxy/handlers.go:69	failed to retrieve the oauth client for authorization	{"error": "missing client secret"}
```

**Comment by gambol99** [comment]
Hi @dlisin ... my bad, this might have gotten removed on a deps upgrade .. I'll double check the go-oidc and if not available update the documentation

**Comment by gambol99** [comment]
https://github.com/gambol99/keycloak-proxy/pull/342
