### ISSUE TITLE
Accessing groups via Google + OIDC

### ISSUE THREAD

**Issue by nabadger** [gambol99/keycloak-proxy#347]
Hi,

Using your example on the README I can get authentication to work via google.

What I'd like is to also perform some additional restriction based on the group(s) of the authenticated user.

As far as I can tell this is not possible on keycloak, as google is only offering `email`, `profile` and `openid` scopes.

Would you be able to confirm this?

**Comment by gambol99** [comment]
Hi @nabadger ... sorry for the massive delay, unfortunately yes, this isn't supported .. I believe [oauth2_proxy](https://github.com/bitly/oauth2_proxy) supports this feature though
