### ISSUE TITLE
Doesn't pass on ip from upstream proxy

### ISSUE THREAD

**Issue by chrisns** [gambol99/keycloak-proxy#36]
If there is a proxy/load balancer above the keycloak proxy, the keycloak proxy does not pass the original ip address on to the app.
see https://github.com/gambol99/keycloak-proxy/blob/master/handlers.go#L388
Should respect a potential `x-forwarded-for` coming from an upstream.

**Comment by gambol99** [comment]
@chrisns ... yep, i guess the proper behavior is to Add rather the overwrite ... I'll look at changing this now ..

**Comment by gambol99** [comment]
#37

**Comment by chrisns** [comment]
wicked, thanks
