### ISSUE TITLE
GoProxy Dependency

### ISSUE THREAD

**Issue by gambol99** [gambol99/keycloak-proxy#363]
Should perhaps think about moving off [github.com/elazarl/goproxy](github.com/elazarl/goproxy) as i'm not sure it's being actively maintained anymore

**Comment by gambol99** [comment]
whats your opinion on this one @abstractj? .. not sure what to do about the goproxy lib

**Comment by abstractj** [comment]
@gambol99 I just can think about some alternatives:

1. Send an e-mail to the author to hopefully get a new release
2. We keep the fork and merge the changes necessary. Later we move and discuss another solution
3. Rewrite the proxy bits, maybe using Gorilla HTTP stack. That would take time.
4. Replace the current dependency by another package like `google/martian`. That would require a rewrite

My take on this is to try 1, if we fail we move to 2 and later plan for step 3 if that makes sense. What do you think?

**Comment by abstractj** [comment]
@gambol99 cool the author merged it for us https://github.com/elazarl/goproxy/commit/077c1cc6f948fbb1a1b6c9576e530c9bcaed25ae

**Comment by gambol99** [comment]
many thanks @abstractj
