### ISSUE TITLE
middleware.go:75:38: multiple-value uuid.NewV1() in single-value context

### ISSUE THREAD

**Issue by wxqsly** [gambol99/keycloak-proxy#394]
Hi, 
When execute **go get github.com/gambol99/keycloak-proxy** today.
It showed me with this error.
_github.com/gambol99/keycloak-proxy
.\middleware.go:75:38: multiple-value uuid.NewV1() in single-value context_

**Comment by gambol99** [comment]
It's trying to compile off the master of [github.com/satori/go.uuid](https://github.com/satori/go.uuid/) where  as the vendor is locked the latest [v1.2.0](https://github.com/satori/go.uuid/releases/tag/v1.2.0) tag (about 3 commits behind) .. Looks like [0ef6afb](https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c) introduced an error in return. Perhaps better to 

```shell
$ go get -u go get github.com/gambol99/keycloak-proxy
$ dep ensure -v
```

**Comment by wxqsly** [comment]
Still not success using above solution.
I had to checkout specified release tag v2.2.2 and build, it works.
