### ISSUE TITLE
Proxyying Grafana: Status 401 - {"message":"Invalid API key"}

### ISSUE THREAD

**Issue by mbecker** [gambol99/keycloak-proxy#404]
Hi,

at first great work ad thanks for your proxy! I know that this repo is not about Grafana or any other application behind the proxy but maybe any other has the similar problem.

I'm using keycloak-proxy for other applications like Kibana, Prometheus, etc. in a Kubernetes environment without any problems. The config listed below works for other applications and Grafana works with keycloak-proxy if the restricted resource is deleted or defined with any other path ("resources=uri=/doeswork").

The config is as follows:

```shell
- --listen=0.0.0.0:3000
- --enable-authorization-header=true
- --enable-forwarding=false
- --discovery-url=https://keycloak.xxx.digital/auth/realms/hello
- --client-id=kubernetes
- --client-secret=4d0462da-5ab3-4665-8b05-9e2ff3f1b448
- --redirection-url=https://grafana.xxx.digital
- --enable-refresh-tokens=true
- --encryption-key=MsVRjD36bfAxfBvHUKUjXOTPXaItDThn    # 32 bytes string
- --upstream-url=http://kube-prometheus-grafana.monitoring:80

### TIMEOUT ###
- --upstream-timeout=100002s
- --upstream-keepalive-timeout=10000s
- --upstream-tls-handshake-timeout=10000s
- --upstream-response-header-timeout=10000s
- --upstream-expect-continue-timeout=10000s
- --server-read-timeout=10000s
- --server-write-timeout=10000s
- --server-idle-timeout=10000s

### Forbidden Page (Template) ###
- --forbidden-page=/opt/templates/html/forbidden_aareon.html.tmpl

### Restricted Resources ###
- --resources=uri=/*|groups=/testadmin

### Whitelistes ####
- --resources=uri=/build*|white-listed=true
- --resources=uri=/build/*|white-listed=true
- --resources=uri=/public*|white-listed=true
- --resources=uri=/public/*|white-listed=true

- --resources=uri=/avatar*|white-listed=true
- --resources=uri=/avatar/*|white-listed=true

- --resources=uri=/api*|white-listed=true
- --resources=uri=/api/*|white-listed=true

- --resources=uri=/login*|white-listed=true
- --resources=uri=/login/*|white-listed=true

- --resources=uri=/api/login*|white-listed=true
- --resources=uri=/api/login/*|white-listed=true

- --resources=uri=/api/dashboards*|white-listed=true
- --resources=uri=/api/dashboards/*|white-listed=true

- --resources=uri=/api/search*|white-listed=true
- --resources=uri=/api/search/*|white-listed=true

- --resources=uri=/api/org*|white-listed=true
- --resources=uri=/api/org/*|white-listed=true

- --resources=uri=/login|white-listed=true
- --resources=uri=/grafana*|white-listed=true
```

The login with keycloak works but unfortunately I do get the following output from Gafana after the redirect:
```json
{"message":"Invalid API key"}
```

The Network tab of Chrome is as follows:
![image](https://user-images.githubusercontent.com/26771/43091977-e9633d60-8eab-11e8-9386-e83503899acb.png)

Does anyone have the same problems with Grafana or any other application behind keycloak-proxy? Or does anyone have some tipps to look at?

I've tried almost any config for Grafana itself but without any success. And Grafana works if the restricted uri is deleted.

Thank you guys!

Update:
Thanks @jangaraj for posting the Grafana config. I've missed it to add it to my original post.

The Grafana Config is as follows:
```shell
### Server ###
- name: GF_SERVER_DOMAIN
  value: grafana.xxx.digital
- name: GF_SERVER_PRTOCOL
  value: "https"
- name: "GF_SERVER_ROOT_URL"
  value: "%(protocol)s://%(domain)s"

### Security ####
- name: GF_SECURITY_ADMIN_USER
  valueFrom:
    secretKeyRef:
      key: user
      name: kube-prometheus-grafana
- name: GF_SECURITY_ADMIN_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: kube-prometheus-grafana
- name: GF_SERVER_ROOT_URL
  value: https://grafana.xxx.digital
#- name: GF_AUTH_BASIC_ENABLED
#  value: "true"
#- name: GF_AUTH_ANONYMOUS_ENABLED
#  value: "true"

### AUTH / PROXY ###
- name: GF_USERS_ALLOW_SIGN_UP
  value: "false"
- name: GF_USERS_AUTO_ASSIGN_ORG
  value: "true"
- name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
  value: "Viewer"
  
- name: GF_AUTH_PROXY_ENABLED
  value: "true"
- name: GF_AUTH_PROXY_HEADER_NAME
  value: "X-Auth-Email"
- name: GF_AUTH_PROXY_HEADER_PROPERTY
  value: "email"
- name: GF_AUTH_PROXY_AUTO_SIGN_UP
  value: "true"
```

**Comment by jangaraj** [comment]
IMHO, you need to configure auth proxy in Grafana, for example:
```
[auth.proxy]
enabled = true
header_name = X-Auth-Email
...
```

**Comment by mbecker** [comment]
HI @jangaraj ,
thanks for posting an example of the Grafana config for Auth Proxy. I've missed to add it and updated the post. The Grafana config includes the "Auth Proxy"-part.

**Comment by jangaraj** [comment]
Try to disable _Authorization_ header in the keycloak-proxy `--enable-authorization-header=false`. I guess that's a root cause of your problem.

**Comment by mbecker** [comment]
Hi @jangaraj ,

thank you very much! Works like expected with disabling "Authorization header".

Maybe that issue could help others with different applications as well.

Thanks!

**Comment by srkfru** [comment]
Good Day @jangaraj,

My issue seems similar to this but configuration bit different than above. can you please look into this https://github.com/IzakMarais/reporter/issues/241  and help me to figure out the root cause.

Thanks,
Srikanta
