### ISSUE TITLE
Option to allow cookie to be sent over insecure connections

### ISSUE THREAD

**Issue by timgent** [gambol99/keycloak-proxy#55]
Newest version of keycloak proxy doesn't allow the cookie to be sent over insecure connections. This is good as default behaviour but it would be good to be able to override this setting as when setting up things in dev it is annoying to need to set up TLS before setting up keycloak proxy

**Comment by gambol99** [comment]
Added in PR #56

**Comment by gambol99** [comment]
@timgent is this what you need?

**Comment by timgent** [comment]
Yep looks good thanks. Could put option in docs too though ;)
