### ISSUE TITLE
docker hub images are not up-to date

### ISSUE THREAD

**Issue by rvion** [gambol99/keycloak-proxy#68]
https://hub.docker.com/r/gambol99/keycloak-proxy/tags/

**Comment by rvion** [comment]
for some reasons, docker-hub still says “Last pushed: 3 months ago"

**Comment by gambol99** [comment]
the builds go to https://quay.io/repository/gambol99/keycloak-proxy ...

**Comment by rvion** [comment]
arf x) 

I think a mention in the readme would be great :)

regarding the current image on hub.docker.com, how about either 
  1. deleting the image on docker hub
  2. manually pushing new images from time to time (like for major releases)
  3 pushing to both quay and docker hub

(Thanks for the quick answers, as always !)

**Comment by gambol99** [comment]
There is a badge at the top, but i'll look at pushing to both ... for some reason though even when I do a successful docker login, docker.io keeps throwing a "authentication required" error
