### ISSUE TITLE
forwarding agent support

### ISSUE THREAD

**Issue by gambol99** [gambol99/keycloak-proxy#75]
Would be nice to have forwarding agent support .. i.e. the proxy loads it logs in, requesting an access token. A application/micro-service seated behind and can proxy through service with the proxy adding the authorization header into the outgoing requests .. We could that verify resource access on the other end.

**Comment by rvion** [comment]
big +1 on that !
I had the need for it yesterday

how about something like `--forward-access-token-as=headername`
