### ISSUE TITLE
[proposal] extend ressource access patterns

### ISSUE THREAD

**Issue by rvion** [gambol99/keycloak-proxy#81]
while reading https://github.com/gambol99/keycloak-proxy/issues/80, I had an idea about extending ressource access declarations

As of now, access policy is declared with a coma separated list of roles names, (`,` meaning `OR`)
```
--resource='uri:/logs/project1|roles=project1,project2'
```

what about replacing `,` with [`+`, `*`, `(`, `)`]

```
--resource='uri:/logs/project1|roles=r1+r2*r3+r4'                # r1 OR (r2 and r3) OR r4
--resource='uri:/logs/project1|roles=r1+r2*(r3+r4+(r5*r6))'    
```

where (`+` and `*` come from logic notation)

 -  `+` being `OR`
 -  `*` being `AND`
 - `(` and `)` allow to nest expressions.

the behaviour is simple and is fully descibed, and it seems powerfull enough to support lots of usage cases.

note: I thought about `+` and `*` to avoid conflicts with  `|`  current usage and `&` meaning in URIs.
(as shown in the example given in https://github.com/gambol99/keycloak-proxy/issues/80, avoiding conflict with `|` and `&` is important so that
 
```
--resource='uri:/logs/%roles%|roles=test1+test2*(test3+test4)
```

correctly match

```
uri:/logs/test1
uri:/logs/test2*test3
uri:/logs/test2*test4
```
 )

------------------

if you like the idea, how about also adding a NOT (`!`) operator so one can use roles to temporarilly ban people, etc.

```
--resource='uri:/logs/project1|roles=!banned
```

**Comment by gambol99** [comment]
Dropped in favor of moving to UMA (plus the complexity of getting this to work with gin)
