### ISSUE TITLE
[proposal] resource syntax normalisation (eg. normalizing "uri:" and "roles=")

### ISSUE THREAD

**Issue by rvion** [gambol99/keycloak-proxy#82]
as of now, ressource syntax read as 
```
--resource='uri:/logs|roles=test1
```

how about unifying the format to something like

```
--resource='uri=/logs|roles=test1|name=rvion|after=2015-03-21T00:18:56Z'
```

documentation would be much easier, and you open gates to feature expansion in an easy way.
I can imagine the `resource`flag becoming `resources` (with an `s`) along some documentation saying

ressources are defined like this:

expr | def
|---------------|----------------------------------|
|`resources` | `ruleset [ ; ruleset ]`|
|`ruleset` | `match [ | match ]`|
|`match` | `check = values`|

checks can be

#### 1. `roles` check

roles= | explanation
|---------------|----------------------------------|
| rolename | any role name you want to grant access |
| expr1 + expr2 | match when either expr1 OR expr2 match  |
| expr1 * expr2 | match when both expr1 AND expr2 match |
| ! expr | negate expression
| (expr) | allow define sub expressions

 - provides `%roles%` to be used in following `ruleset`s

example:
...

#### 2.`uri` check

uri= | explanation
|---------------|----------------------------------|
| segment [ / segment]  | |
| * | * match one segment |
| ** | ** match any number of segment |

provides %url% 
provides %last-segment% to following `ruleset`s

------------------

👍  each ruleset would provide template for next ruleset, so implementation would be very easy, with no dependency resolution to do. if you want to use %role% in uri, or in whatever else, you just have to write your resource with ruleset in the correct order for keycloak-proxy to resolve them.

👍 it becomes very easy to write things like

```
--resources="roles=user"
```
when you only want to take roles into account.

no more
```
--resources="uri:/|roles=user""
``` 
when uri doesn't matter.

👍 yaml implementation should be very straighforward too as there is a direct encoding.

**Comment by gambol99** [comment]
I like the idea!!! ... It's probably worth moving this into a generic rbac package ..
