### ISSUE TITLE
proxy protocol

### ISSUE THREAD

**Issue by gambol99** [gambol99/keycloak-proxy#84]
i've been meaning to do this for a well but adding proxy protocol is a desirable

**Comment by rvion** [comment]
related links people like me (interested in the discussion, but not expert (yet)): 
 - http://blog.haproxy.com/haproxy/proxy-protocol/
 - http://www.haproxy.org/download/1.7/doc/proxy-protocol.txt

**Comment by gambol99** [comment]
[go-proxyprotocol](https://github.com/armon/go-proxyproto) looks promising, though might be somewhat fiddly get to working with gin

**Comment by gambol99** [comment]
enabled in https://github.com/gambol99/keycloak-proxy/commit/8ac53a39c0c9f5d021ad41283dac424512c622db
