### ISSUE TITLE
Using HTTP Authorization bearer header to bypass proxy?

### ISSUE THREAD

**Issue by maslick** [gambol99/keycloak-proxy#87]
Hi, is there an opportunity to pass the keycloak-proxy programmatically by specifying an Authorization Bearer header in the HTTP request?

**Comment by gambol99** [comment]
hi @maslick .. do you mean passing the access token via a bearer token? ... i.e "Authorization: Bearer ENCODE_ACCESS_TOKEN" ... The code for extracting the session is [here](https://github.com/gambol99/keycloak-proxy/blob/master/session.go#L29) .. It will first try for a cookie and if not found, check for a Authorization header

**Comment by maslick** [comment]
hi @gambol99, i mean if you are using curl, not the browser.

**Comment by gambol99** [comment]
@maslick ... curl -H "Authorization: Bearer ENCODE_ACCESS_TOKEN" https://side .. or do you mean can you login from the command line? .. There's a login endpoint assuming you using a oauth2 provider whom supports grant_type=password

```shell
/oauth/login provides a relay endpoint to login via grant_type=password i.e. POST /oauth/login?username=USERNAME&password=PASSWORD
```

**Comment by maslick** [comment]
aha cool. so this ``POST /oauth/login?username=USERNAME&password=PASSWORD`` will return authorization_code or token?

**Comment by gambol99** [comment]
@maslick the endpoint will respond with an access token (spec [RFC6749](https://tools.ietf.org/html/rfc6749#section-4.3)) .. If your provider is keycloak it requires 'direct access grants' enabled.

**Comment by gambol99** [comment]
hi @maslick  ... can i close this one?
