### ISSUE TITLE
Developer guide

### ISSUE THREAD

**Issue by timgent** [gambol99/keycloak-proxy#89]
Could do with a section on building locally and contributing. Sure I am doing something wrong but after running:
```
go get
go install
go build
docker build .
docker run xxxxx
```
I get:
```
docker: Error response from daemon: Container command '/opt/keycloak-proxy' not found or does not exist..
```

**Comment by gambol99** [comment]
Added a Building section in the readme ... essentially, go and make is enough or make docker-build
